if(MSVC)
    include(${CMAKE_CURRENT_LIST_DIR}/WindowsMSVC.cmake)
elseif(WIN32 AND CMAKE_COMPILER_IS_GNUCXX)
    include(${CMAKE_CURRENT_LIST_DIR}/WindowsGCC.cmake)
elseif(APPLE)
    include(${CMAKE_CURRENT_LIST_DIR}/MacOS.cmake)
elseif(UNIX AND "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    include(${CMAKE_CURRENT_LIST_DIR}/LinuxClang.cmake)
elseif(UNIX)
    include(${CMAKE_CURRENT_LIST_DIR}/LinuxGCC.cmake)
else()
    message(WARNING "Unsupported platform/compiler combination")
endif()