set(GLBINDING_ROOT ${PROJECT_SOURCE_DIR}/Extern/glbinding-2.1.1)

set(GLBINDING_INCLUDE_DIR ${GLBINDING_ROOT}/include)
set(GLBINDING_LIBRARIES ${GLBINDING_ROOT}/lib/release/${DELIBERATION_BUILD_TARGET_OS}/${DELIBERATION_BUILD_COMPILER_PLATFORM}/libglbinding.a)

set(GLBINDING_LIBRARIES ${GLBINDING_LIBRARIES})
